---
- name: Install apache on webservers
  hosts: all
  become: true
  tasks:
  - name: Install httpd package
    yum:
       name: httpd
       state: installed
    when: ansible_os_family == "RedHat"
    tags: install_apache

  - name: Start httpd service
    service: 
        name: httpd
        state: started
    when: ansible_os_family == "RedHat"
    tags: start_service

  - name: Install apache2 package
    apt: 
        name: apache2
        state: present
    when: ansible_os_family == "Debian"
    tags: install_apache

  - name: Start Apache2 service
    service: 
        name: apache2
        state: started
    when: ansible_os_family == "Debian"
    tags: start_service

  - name: copy files
    copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        mode: 0666 
