--- 
- name: this playbook creates users
  hosts: 172.31.32.164 
  become: true
  tasks:
  - name: creating user accounts
    user:
      name: "{{ item }}"
      state: present 
    with_items:
     -  user1
     -  user2
     -  user3      
